theme: Jekyll-theme-merlot
title: "Mi Portafolio"
author: "Tu Nombre"
description: "Bienvenido a mi página oficial de GitHub. Aquí comparto mis proyectos y aprendizajes."
baseurl: ""
url: "https://Dave-Torres25.github.io"
