body {
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
    color: #333;
    max-width: 800px;
    margin: auto;
    padding: 20px;
}

h1 {
    color: #0073e6;
}

a {
    color: #0073e6;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
